#on:
#  push:
#    branches:
#      - master
on:
  workflow_dispatch:
    inputs:
      tmux-version:
        description: 'Which tmux version to build?'
        required: true
        default: '3.3'
jobs:
  build:
    runs-on: ubuntu-latest
    name: build tmux app image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build . -t tmux --build-arg TMUX_TAG=${{ inputs.tmux-version }}
          docker create -ti --name tmuxcontainer tmux bash
          docker cp tmuxcontainer:/opt/releases/tmux-${{ inputs.tmux-version }}-x86_64.AppImage .
      - name: save artifact
        uses: actions/upload-artifact@v2
        with:
          name: tmux.AppImage
          path: tmux-*.AppImage
