on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: build tmux app image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build . -t tmux
          docker create -ti --name tmuxcontainer tmux bash
          docker cp tmuxcontainer:/opt/releases/tmux-3.1c-x86_64.AppImage .
      - name: save artifact
        uses: actions/upload-artifact@v2
        with:
          name: tmux.AppImage
          path: tmux-*.AppImage
